using GrpcScaffold.Core.Analysis.Models;
using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace GrpcScaffold.Core.Generation;


public sealed class ContractGenerator
{
    public string GenerateRequest(
        EndpointModel endpoint,
        string serviceName,
        string ns)
    {
        if (endpoint.Request is null)
            return string.Empty;

        return GenerateContract(
            endpoint.Request,
            serviceName,
            ns);
    }

    public string GenerateResponse(
        EndpointModel endpoint,
        string serviceName,
        string ns)
    {
        if (endpoint.Response is null)
            return string.Empty;

        return GenerateContract(
            endpoint.Response,
            serviceName,
            ns);
    }

    private static string GenerateContract(
        ContractInfo contract,
        string serviceName,
        string ns)
    {
        var type = contract.ClrType;

        if (type is not INamedTypeSymbol namedType)
            throw new InvalidOperationException(
                $"Contract type '{type.ToDisplayString()}' is not a named type.");

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();

        sb.Append("namespace ")
            .Append(ns)
            .Append(".Grpc.Contracts.The")
            .Append(serviceName)
            .AppendLine(";");

        sb.AppendLine();

        sb.Append("public sealed record ")
            .Append(contract.Name.Replace("Query","").Replace("Command", ""))
            .AppendLine();

        sb.AppendLine("{");

        foreach (var property in namedType.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic)
                continue;

            if (property.DeclaredAccessibility != Accessibility.Public)
                continue;

            sb.Append("    public ")
                .Append(property.Type.ToDisplayString(
                    SymbolDisplayFormat.MinimallyQualifiedFormat))
                .Append(' ')
                .Append(property.Name)
                .AppendLine(" { get; init; }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}