using GrpcScaffold.Core.Analysis.Models;
using Microsoft.CodeAnalysis;
using System.Text;

namespace GrpcScaffold.Core.Generation;

public sealed class ContractGenerator
{
    public string GenerateRequest(EndpointModel endpoint, string ns)
    {
        if (endpoint.Request is null)
            return string.Empty;

        return GenerateContract(endpoint.Request, ns);
    }

    public string GenerateResponse(EndpointModel endpoint, string ns)
    {
        if (endpoint.Response is null)
            return string.Empty;

        return GenerateContract(endpoint.Response, ns);
    }

    public IReadOnlyList<(string FileName, string Content)> GenerateContracts(ContractInfo? contract, string ns)
    {
        if (contract is null)
            return [];

        var generated = Flatten(contract)
            .GroupBy(c => c.Name, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(c => c.Name, StringComparer.Ordinal)
            .Select(c => ($"{c.Name}.g.cs", GenerateContract(c, ns)))
            .ToList();

        generated.AddRange(CollectEnums(contract)
            .GroupBy(e => e.Name, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(e => e.Name, StringComparer.Ordinal)
            .Select(e => ($"{e.Name}.g.cs", GenerateEnum(e, ns))));

        return generated;
    }

    private static IEnumerable<ContractInfo> Flatten(ContractInfo root)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var stack = new Stack<ContractInfo>();
        stack.Push(root);

        while (stack.Count > 0)
        {
            var current = stack.Pop();
            var key = current.ClrType.ToDisplayString();
            if (!seen.Add(key))
                continue;

            yield return current;

            foreach (var dependency in current.Dependencies.Reverse())
                stack.Push(dependency);
        }
    }

    private static IEnumerable<INamedTypeSymbol> CollectEnums(ContractInfo root)
    {
        foreach (var contract in Flatten(root))
        {
            foreach (var field in contract.Fields)
                foreach (var enumType in CollectEnums(field.Reference))
                    yield return enumType;
        }
    }

    private static IEnumerable<INamedTypeSymbol> CollectEnums(ProtoTypeReference reference)
    {
        if (reference.IsEnum && reference.ClrType is INamedTypeSymbol enumType)
            yield return enumType;

        if (reference.ElementType is not null)
        {
            foreach (var item in CollectEnums(reference.ElementType))
                yield return item;
        }

        foreach (var argument in reference.GenericArguments)
        {
            foreach (var item in CollectEnums(argument))
                yield return item;
        }
    }

    private static string GenerateEnum(INamedTypeSymbol enumType, string ns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by grpc-scaffold.");
        sb.AppendLine("//   Safe to regenerate.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("public enum ").Append(enumType.Name).AppendLine();
        sb.AppendLine("{");

        var values = enumType.GetMembers().OfType<IFieldSymbol>()
            .Where(f => f.HasConstantValue)
            .OrderBy(f => Convert.ToInt64(f.ConstantValue), Comparer<long>.Default)
            .ToList();

        for (var i = 0; i < values.Count; i++)
        {
            var value = values[i];
            sb.Append("    ").Append(value.Name).Append(" = ").Append(Convert.ToInt64(value.ConstantValue));
            if (i < values.Count - 1)
                sb.Append(',');
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateContract(ContractInfo contract, string ns)
    {
        var type = contract.ClrType;

        if (type is not INamedTypeSymbol namedType)
            throw new InvalidOperationException($"Contract type '{type.ToDisplayString()}' is not a named type.");

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by grpc-scaffold.");
        sb.AppendLine("//   Safe to regenerate.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.Append("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("public sealed record ").Append(contract.Name).AppendLine();
        sb.AppendLine("{");

        foreach (var property in GetAllProperties(namedType)
    .GroupBy(p => p.Name, StringComparer.Ordinal)
    .Select(g => g.First())
    .OrderBy(p => p.Name, StringComparer.Ordinal))
        {
            sb.Append("    public ")
                .Append(ToContractType(property.Type, ns))
                .Append(property.NullableAnnotation == NullableAnnotation.Annotated && property.Type.IsReferenceType ? "?" : string.Empty)
                .Append(' ')
                .Append(property.Name)
                .Append(" { get; init; }");

            if (NeedsInitializer(property.Type, property.NullableAnnotation))
                sb.Append(" = ").Append(GetInitializer(property.Type, ns)).Append(';');

            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToContractType(ITypeSymbol type, string contractNamespace)
    {
        if (type is IArrayTypeSymbol array)
            return $"{ToContractType(array.ElementType, contractNamespace)}[]";

        if (type is INamedTypeSymbol { IsGenericType: true } named)
        {
            if (named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                return $"{ToContractType(named.TypeArguments[0], contractNamespace)}?";

            var args = string.Join(", ", named.TypeArguments.Select(t => ToContractType(t, contractNamespace)));
            var definition = named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var tick = definition.IndexOf('<');
            if (tick >= 0)
                definition = definition[..tick];

            return $"{definition}<{args}>";
        }

        if (type.TypeKind is TypeKind.Class or TypeKind.Enum ||
            type.TypeKind == TypeKind.Struct && type.SpecialType == SpecialType.None)
        {
            if (!string.IsNullOrWhiteSpace(contractNamespace) &&
                type.ContainingNamespace?.ToDisplayString() is { } ns && ns != "System")
                return $"global::{contractNamespace}.{type.Name}";
        }

        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static bool NeedsInitializer(ITypeSymbol type, NullableAnnotation nullableAnnotation)
    {
        if (nullableAnnotation == NullableAnnotation.Annotated)
            return false;

        if (type.SpecialType == SpecialType.System_String)
            return true;

        if (type is IArrayTypeSymbol)
            return true;

        if (type is INamedTypeSymbol { IsGenericType: true } named &&
            named.Name is "List" or "IList" or "ICollection" or "IEnumerable" or "IReadOnlyCollection" or "IReadOnlyList")
            return true;

        return type.IsReferenceType;
    }

    private static string GetInitializer(ITypeSymbol type, string contractNamespace)
    {
        if (type.SpecialType == SpecialType.System_String)
            return "string.Empty";

        if (type is IArrayTypeSymbol array)
            return $"System.Array.Empty<{ToContractType(array.ElementType, contractNamespace)}>()";

        if (type is INamedTypeSymbol { IsGenericType: true } named && named.TypeArguments.Length == 1)
            return "[]";

        return "default!";
    }
    private static IEnumerable<IPropertySymbol> GetAllProperties(INamedTypeSymbol type)
    {
        var types = new Stack<INamedTypeSymbol>();

        for (var current = type;
             current is not null;
             current = current.BaseType)
        {
            types.Push(current);
        }

        while (types.Count > 0)
        {
            var current = types.Pop();

            foreach (var property in current.GetMembers()
                         .OfType<IPropertySymbol>()
                         .Where(static p =>
                             p is
                             {
                                 IsStatic: false,
                                 DeclaredAccessibility: Accessibility.Public,
                                 GetMethod: not null
                             }))
            {
                yield return property;
            }
        }
    }
}
