using FileCreator.Core;
using FileCreator.Core.DependencyInjection;
using FileCreator.Core.Generation;
using FileCreator.Core.Generators;
using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;

public sealed class FileCreatorGeneratorIntegrationTests
{
    [Fact]
    public async Task Full_generic_pipeline_returns_ordered_byte_stable_artifacts()
    {
        using var services = new ServiceCollection()
            .AddScribanCodeGeneration()
            .BuildServiceProvider();
        var root = Path.Combine(Path.GetTempPath(), "filecreator-generation", "stable-fixture");
        var request = new FileCreatorGenerationRequest(
            ProjectName: "Demo",
            GroupName: GroupName.Create("Region"),
            UseCaseName: "List",
            UseCasesPath: Path.Combine(root, "UseCases"),
            WebPath: Path.Combine(root, "Web"),
            FunctionalTestsPath: Path.Combine(root, "FunctionalTests"),
            UnitTestsPath: Path.Combine(root, "UnitTests"),
            InfrastructurePath: Path.Combine(root, "Infrastructure"),
            HasRequest: true,
            RequestType: RequestType.Query,
            HasResponse: true,
            ResponseType: ResponseType.PagedList,
            HttpVerb: HttpVerb.GET);
        var generator = new FileCreatorGenerator(
            request,
            services.GetRequiredService<ScribanFileCreator>());

        var first = await generator.GeneratePreview();
        var second = await generator.GeneratePreview();

        first.Should().HaveCount(12);
        first.Select(file => file.AbsolutePath).Should().BeInAscendingOrder(StringComparer.OrdinalIgnoreCase);
        first.Select(file => file.AbsolutePath).Should().OnlyHaveUniqueItems();
        first.Should().OnlyContain(file => file.Content.StartsWith("// <auto-generated>", StringComparison.Ordinal));
        second.Select(file => (file.AbsolutePath, file.Content))
            .Should().Equal(first.Select(file => (file.AbsolutePath, file.Content)));
    }
}
