using FileCreator.Core.Generation;
using FluentAssertions;

public sealed class GeneratedFileWriterTests : IDisposable
{
    private readonly string _root = Path.Combine(
        Path.GetTempPath(),
        "filecreator-tests",
        Guid.NewGuid().ToString("N"));

    [Fact]
    public void Write_creates_then_skips_unchanged_content()
    {
        var writer = new GeneratedFileWriter();
        var file = new GeneratedFile(_root, "Generated/Test.cs", Owned("one"));

        writer.Write([file]).Single().Status.Should().Be(GeneratedFileWriteStatus.Created);
        writer.Write([file]).Single().Status.Should().Be(GeneratedFileWriteStatus.Unchanged);
    }

    [Fact]
    public void Create_only_preserves_an_existing_file()
    {
        var writer = new GeneratedFileWriter();
        var path = Path.Combine(_root, "Generated", "Test.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, "handwritten");

        var result = writer.Write([
            new GeneratedFile(_root, "Generated/Test.cs", Owned("replacement"))
        ]).Single();

        result.Status.Should().Be(GeneratedFileWriteStatus.SkippedExisting);
        File.ReadAllText(path).Should().Be("handwritten");
    }

    [Fact]
    public void Overwrite_generated_refuses_a_handwritten_file()
    {
        var writer = new GeneratedFileWriter();
        var path = Path.Combine(_root, "Generated", "Test.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, "handwritten");

        var action = () => writer.Write(
            [new GeneratedFile(_root, "Generated/Test.cs", Owned("replacement"))],
            GeneratedFileWritePolicy.OverwriteGenerated);

        action.Should().Throw<GenerationException>()
            .Which.Diagnostic.Code.Should().Be("FC1004");
        File.ReadAllText(path).Should().Be("handwritten");
    }

    [Fact]
    public void Duplicate_output_paths_are_diagnosed()
    {
        var writer = new GeneratedFileWriter();
        var files = new[]
        {
            new GeneratedFile(_root, "Generated/Test.cs", Owned("one")),
            new GeneratedFile(_root, "Generated/Test.cs", Owned("two"))
        };

        var action = () => writer.Write(files);

        action.Should().Throw<GenerationException>()
            .Which.Diagnostic.Code.Should().Be("FC1002");
    }

    [Fact]
    public void Artifact_paths_cannot_escape_the_output_root()
    {
        var action = () => new GeneratedFile(_root, "../outside.cs", "content");

        action.Should().Throw<ArgumentException>();
    }

    public void Dispose()
    {
        if (Directory.Exists(_root))
            Directory.Delete(_root, recursive: true);
    }

    private static string Owned(string value) =>
        $"// <auto-generated>{Environment.NewLine}" +
        $"// Generated by FileCreator{Environment.NewLine}" +
        $"// </auto-generated>{Environment.NewLine}" + value;
}
