using FluentAssertions;
using GrpcScaffold.Core.IO;

public sealed class IdempotentFileWriterTests : IDisposable
{
    private readonly string _root = Path.Combine(
        Path.GetTempPath(),
        "grpc-scaffold-tests",
        Guid.NewGuid().ToString("N"));

    [Fact]
    public void First_run_does_not_overwrite_a_handwritten_collision()
    {
        var path = Path.Combine(_root, "Grpc", "Service.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, "handwritten");
        var writer = new IdempotentFileWriter(_root, force: false, strict: false, dryRun: false);

        var result = writer.Apply([
            new WritePlan("Grpc/Service.cs", path, Generated("replacement"), WriteMode.FullOverwrite)
        ]).Single();

        result.ManualEditDetected.Should().BeTrue();
        result.Written.Should().BeFalse();
        File.ReadAllText(path).Should().Be("handwritten");
    }

    [Fact]
    public void Generated_output_is_byte_stable_across_two_runs()
    {
        var path = Path.Combine(_root, "Grpc", "Service.cs");
        var plan = new WritePlan("Grpc/Service.cs", path, Generated("content"), WriteMode.FullOverwrite);

        new IdempotentFileWriter(_root, false, false, false)
            .Apply([plan]).Single().Written.Should().BeTrue();
        var second = new IdempotentFileWriter(_root, false, false, false)
            .Apply([plan]).Single();

        second.WasUnchanged.Should().BeTrue();
        second.Written.Should().BeFalse();
    }

    [Fact]
    public void Output_paths_cannot_escape_the_configured_root()
    {
        var path = Path.GetFullPath(Path.Combine(_root, "..", "outside.cs"));
        var writer = new IdempotentFileWriter(_root, false, false, false);

        var action = () => writer.Apply([
            new WritePlan("../outside.cs", path, Generated("content"), WriteMode.FullOverwrite)
        ]);

        action.Should().Throw<InvalidOperationException>();
    }

    public void Dispose()
    {
        if (Directory.Exists(_root))
            Directory.Delete(_root, recursive: true);
    }

    private static string Generated(string value) =>
        $"// <auto-generated>{Environment.NewLine}" +
        $"// Generated by grpc-scaffold{Environment.NewLine}" +
        $"// </auto-generated>{Environment.NewLine}" + value;
}
