using FileCreator.Core;
using FileCreator.Core.Generation;
using FileCreator.Core.Templates.Factories;
using FileCreator.Core.Templates.Generators;
using FileCreator.Core.Templating;
using FluentAssertions;

public sealed class ScribanGenerationPipelineTests
{
    [Fact]
    public async Task Endpoint_generation_is_deterministic_and_owned_by_filecreator()
    {
        var renderer = new ScribanTemplateRenderer(new EmbeddedResourceTemplateSource());
        var generator = new EndpointGenerator(renderer);
        var model = EndpointTemplateModelFactory.Create(
            projectName: "Demo",
            useCaseNamespace: "Demo.UseCases.TheRegion.Commands.Create",
            webNamespace: "Demo.Web.EndPoints.Regions.Create",
            group: "TheRegion",
            useCaseName: "Create",
            requestType: RequestType.Command,
            httpVerb: HttpVerb.POST,
            hasRequest: true,
            hasResponse: true,
            responseType: ResponseType.Single);

        var first = await generator.GenerateAsync(model);
        var second = await generator.GenerateAsync(model);

        second.Should().Be(first);
        first.Should().StartWith("// <auto-generated>");
        first.Should().Contain("Generated by FileCreator");
        first.Should().Contain("public sealed class CreateEndpoint");
        first.Should().Contain("Endpoint<CreateRequest>");
    }

    [Fact]
    public async Task Request_generation_uses_the_canonical_scriban_generator()
    {
        var renderer = new ScribanTemplateRenderer(new EmbeddedResourceTemplateSource());
        var model = EndpointRequestTemplateModelFactory.Create(
            ns: "Demo.Web.EndPoints.Regions.Create",
            useCaseNameSpace: "Demo.UseCases.TheRegion.Commands.Create",
            useCaseName: "Create",
            requestType: RequestType.Command,
            hasResponse: true,
            responseType: ResponseType.Single);

        var rendered = await renderer.RenderAsync("endpoint-request.sbn", model);
        var output = RoslynCodeFormatter.Format(rendered);

        output.Should().StartWith("// <auto-generated>");
        output.Should().Contain("public sealed class CreateRequest");
        output.Should().Contain("CreateCommand MapToCommand(");
        output.Should().Contain("CreateRequest request");
    }

    [Fact]
    public void Invalid_generation_input_produces_structured_diagnostics()
    {
        var request = new FileCreatorGenerationRequest(
            ProjectName: "Demo",
            GroupName: GroupName.Create("Region"),
            UseCaseName: "List",
            UseCasesPath: "use-cases",
            WebPath: "web",
            FunctionalTestsPath: "functional-tests",
            UnitTestsPath: "unit-tests",
            InfrastructurePath: "infrastructure",
            HasRequest: true,
            RequestType: RequestType.Command,
            HasResponse: true,
            ResponseType: ResponseType.PagedList,
            HttpVerb: HttpVerb.POST);

        var diagnostic = request.Validate().Single();

        diagnostic.Code.Should().Be("FC1101");
        diagnostic.Severity.Should().Be(GenerationDiagnosticSeverity.Error);
    }

    [Fact]
    public void Invalid_template_output_is_reported_before_file_output()
    {
        var action = () => RoslynCodeFormatter.Format("public class Broken {");

        action.Should().Throw<GenerationException>()
            .Which.Diagnostic.Code.Should().Be("FC1201");
    }
}
