using System.Text;

namespace FileCreator.Core.Generation;

public enum GeneratedFileWritePolicy
{
    CreateOnly,
    OverwriteGenerated,
    FailIfExists
}

public enum GeneratedFileWriteStatus
{
    Created,
    Overwritten,
    Unchanged,
    SkippedExisting
}

public sealed record GeneratedFileWriteResult(string RelativePath, GeneratedFileWriteStatus Status);

/// <summary>
/// The generic FileCreator output boundary. It writes in deterministic path order, skips
/// byte-identical files, and never overwrites a handwritten file.
/// </summary>
public sealed class GeneratedFileWriter
{
    private static readonly UTF8Encoding Utf8WithoutBom = new(encoderShouldEmitUTF8Identifier: false);

    public IReadOnlyList<GeneratedFileWriteResult> Write(
        IEnumerable<GeneratedFile> files,
        GeneratedFileWritePolicy policy = GeneratedFileWritePolicy.CreateOnly)
    {
        ArgumentNullException.ThrowIfNull(files);

        var ordered = files
            .OrderBy(file => file.AbsolutePath, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var duplicate = ordered
            .GroupBy(file => file.AbsolutePath, StringComparer.OrdinalIgnoreCase)
            .FirstOrDefault(group => group.Count() > 1);

        if (duplicate is not null)
        {
            throw new GenerationException(new GenerationDiagnostic(
                GenerationDiagnosticSeverity.Error,
                "FC1002",
                $"Multiple generated artifacts target '{duplicate.Key}'.",
                Source: duplicate.Key,
                SuggestedFix: "Ensure each generator returns a unique relative path."));
        }

        var results = new List<GeneratedFileWriteResult>(ordered.Count);
        foreach (var file in ordered)
            results.Add(Write(file, policy));

        return results;
    }

    private static GeneratedFileWriteResult Write(
        GeneratedFile file,
        GeneratedFileWritePolicy policy)
    {
        if (!File.Exists(file.AbsolutePath))
        {
            Persist(file);
            return new(file.RelativePath, GeneratedFileWriteStatus.Created);
        }

        var existing = File.ReadAllText(file.AbsolutePath);
        if (string.Equals(existing, file.Content, StringComparison.Ordinal))
            return new(file.RelativePath, GeneratedFileWriteStatus.Unchanged);

        if (policy == GeneratedFileWritePolicy.CreateOnly)
            return new(file.RelativePath, GeneratedFileWriteStatus.SkippedExisting);

        if (policy == GeneratedFileWritePolicy.FailIfExists)
        {
            throw new GenerationException(new GenerationDiagnostic(
                GenerationDiagnosticSeverity.Error,
                "FC1003",
                $"The output file '{file.AbsolutePath}' already exists.",
                Source: file.AbsolutePath,
                SuggestedFix: "Choose CreateOnly or OverwriteGenerated explicitly."));
        }

        if (!IsOwnedByFileCreator(existing))
        {
            throw new GenerationException(new GenerationDiagnostic(
                GenerationDiagnosticSeverity.Error,
                "FC1004",
                $"Refusing to overwrite handwritten file '{file.AbsolutePath}'.",
                Source: file.AbsolutePath,
                SuggestedFix: "Move the file or add the FileCreator generated header only if the file is generator-owned."));
        }

        Persist(file);
        return new(file.RelativePath, GeneratedFileWriteStatus.Overwritten);
    }

    private static bool IsOwnedByFileCreator(string content) =>
        content.Contains("<auto-generated>", StringComparison.Ordinal) &&
        content.Contains("Generated by FileCreator", StringComparison.Ordinal);

    private static void Persist(GeneratedFile file)
    {
        var directory = Path.GetDirectoryName(file.AbsolutePath)
            ?? throw new InvalidOperationException($"No directory exists for '{file.AbsolutePath}'.");

        Directory.CreateDirectory(directory);
        File.WriteAllText(file.AbsolutePath, file.Content, Utf8WithoutBom);
    }
}
