<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<StartupObject>FileCreator.Program</StartupObject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FastColoredTextBox.NET10" Version="2.16.26.9180" />
		<PackageReference Include="Humanizer" Version="3.0.1" />
		<PackageReference Include="Humanizer.Core" Version="3.0.1" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.0.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.0.1" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.0.0" />
		<PackageReference Include="Duende.IdentityServer" Version="7.3.1"/>

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FileCreator.Core\FileCreator.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="Properties\Settings.settings">
			<Generator>PublicSettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>

</Project>