// src/GrpcScaffold.Core/IO/IdempotentFileWriter.cs
using System.Security.Cryptography;
using System.Text;

namespace GrpcScaffold.Core.IO;

public enum WriteMode { FullOverwrite, RegionMerge }

public sealed record WritePlan(string RelativePath, string AbsolutePath, string Content, WriteMode Mode);

public sealed record WriteResult(string RelativePath, bool Written, bool WasUnchanged, bool ManualEditDetected);

public sealed class IdempotentFileWriter(string outputRoot, bool force, bool strict, bool dryRun)
{
    private static readonly UTF8Encoding Utf8WithoutBom = new(encoderShouldEmitUTF8Identifier: false);
    private readonly string _outputRoot = Path.GetFullPath(outputRoot);
    private readonly string _manifestPath = Path.Combine(Path.GetFullPath(outputRoot), ".grpc-scaffold", "manifest.json");
    private readonly GenerationManifest _manifest = GenerationManifest.Load(
        Path.Combine(outputRoot, ".grpc-scaffold", "manifest.json"));

    public IReadOnlyList<WriteResult> Apply(IEnumerable<WritePlan> plans)
    {
        var results = new List<WriteResult>();

        foreach (var plan in plans.OrderBy(plan => plan.RelativePath, StringComparer.Ordinal))
        {
            ValidatePath(plan);

            var existing = File.Exists(plan.AbsolutePath) ? File.ReadAllText(plan.AbsolutePath) : null;
            var knownHash = _manifest.FileHashes.GetValueOrDefault(plan.RelativePath);
            var manualEditDetected = existing is not null &&
                (knownHash is not null
                    ? Hash(existing) != knownHash
                    : plan.Mode == WriteMode.FullOverwrite && !IsGenerated(existing));

            string finalContent = plan.Mode switch
            {
                _ when manualEditDetected && !force => existing!,
                WriteMode.FullOverwrite => plan.Content,
                WriteMode.RegionMerge when existing is null => plan.Content,
                WriteMode.RegionMerge => RegionMerger.Merge(existing!, plan.Content),
                _ => plan.Content
            };

            var unchanged = existing == finalContent;

            if (manualEditDetected && strict && !force)
            {
                results.Add(new WriteResult(plan.RelativePath, Written: false, unchanged, ManualEditDetected: true));
                continue;
            }

            if (!unchanged && !dryRun)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(plan.AbsolutePath)!);
                File.WriteAllText(plan.AbsolutePath, finalContent, Utf8WithoutBom);
                _manifest.FileHashes[plan.RelativePath] = Hash(finalContent);
            }
            else if (existing is not null && knownHash is null && !manualEditDetected && !dryRun)
            {
                _manifest.FileHashes[plan.RelativePath] = Hash(existing);
            }

            results.Add(new WriteResult(plan.RelativePath, Written: !unchanged && !dryRun, unchanged, manualEditDetected));
        }

        if (!dryRun)
            _manifest.Save(_manifestPath);

        return results;
    }

    private static string Hash(string content) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content)));

    private static bool IsGenerated(string content) =>
        content.Contains("<auto-generated>", StringComparison.Ordinal) &&
        content.Contains("Generated by grpc-scaffold", StringComparison.Ordinal);

    private void ValidatePath(WritePlan plan)
    {
        if (Path.IsPathRooted(plan.RelativePath))
            throw new InvalidOperationException($"Generated path '{plan.RelativePath}' must be relative.");

        var absolutePath = Path.GetFullPath(plan.AbsolutePath);
        var relativeToRoot = Path.GetRelativePath(_outputRoot, absolutePath);
        if (relativeToRoot == ".." ||
            relativeToRoot.StartsWith($"..{Path.DirectorySeparatorChar}", StringComparison.Ordinal) ||
            Path.IsPathRooted(relativeToRoot))
        {
            throw new InvalidOperationException(
                $"Generated path '{plan.AbsolutePath}' escapes output root '{_outputRoot}'.");
        }
    }
}
